services:
  postgres:
    image: postgres:16
    container_name: reviewmind-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reviewmind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - reviewmind_postgres_data:/var/lib/postgresql/data

volumes:
  reviewmind_postgres_data: