spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewmind
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

fastapi:
  url: http://localhost:8000

gemini:
  api-key: "AIzaSyDsClGMRnXoSRRi9qJJ_XAIpdbtlNsIGQ4"